DATA_DIR: '/mounts/Datasets1/ChallengeDeep'
OUTPUT_DIR: '../models'
DATASET:
  DATA_FORMAT: jpg
  PREPROCESSING:
    CHANNELS: 1
    REVERSE_COLOR: False
    SQUARE_PADDING:
      ACTIVE: False
      INPUT_SIZE: 300
    RESIZE_CROP:
      ACTIVE: True
      INPUT_SIZE: 128
    RESIZE:
      ACTIVE: False
      INPUT_SIZE: 64
    NORMALIZE:
      ACTIVE: True
    FLIP:
      HORIZONTAL:
        ACTIVE: True
        VALUE: 0.5
      VERTICAL:
        ACTIVE: True
        VALUE: 0.5
    AFFINE:
      ACTIVE: True
      DEGREES: 40
      TRANSLATE: [0.2, 0.2]
  BATCH_SIZE: 256
  VALID_RATIO: 0.2
  SMART_SPLIT: True
  VERBOSITY: True
  NUM_THREADS: 8
  NUM_CLASSES: 86
  ROOT: 'data/'
  TEST: test
  TRAIN: train
TRAIN:
  EPOCH: 100
  CHECKPOINT_STEP: 10
  LOG_DIR: 'tensorboard/metrics'
  SAVE_DIR: '../models'
  MODEL: 'ConvNet'
  LR_INITIAL : 0.001
  LR_DECAY: 0.01
  LR_PATIENCE : 5
  LOAD_MODEL:
    ACTIVE: False
    PATH_TO_MODEL: '../models/ConvNet_0/best_model.pth'
TEST:
  BATCH_SIZE: 64
  PATH_TO_MODEL: '../models/convnet/epoch_49_model.pth'
  PATH_TO_CSV: './test_convnet.csv'
