DATA_DIR: '../data'
OUTPUT_DIR: '../models'
DATASET:
  DATA_FORMAT: jpg
  PREPROCESSING:
    SQUARE_PADDING:
      ACTIVE: True
      INPUT_SIZE: 300
    RESIZE_CROP:
      ACTIVE: False
      INPUT_SIZE: 128
    NORMALIZE: True
    FLIP:
      HORIZONTAL:
        ACTIVE: True
        VALUE: 0.5
      VERTICAL:
        ACTIVE: True
        VALUE: 0.5
    AFFINE:
      ACTIVE: True
      DEGREES: 40
      TRANSLATE: [0.2, 0.2]
  BATCH_SIZE: 256
  VALID_RATIO: 0.2
  SMART_SPLIT: True
  VERBOSITY: True
  NUM_THREADS: 4
  NUM_CLASSES: 86
  ROOT: 'data/'
  TEST: test
  TRAIN: train
TRAIN:
  EPOCH: 10
  LOG_DIR: 'tensorboard/metrics'
  SAVE_DIR: '../models'
TEST:
  PATH_TO_MODEL: '../models/linear_0/best_model.pth'
  PATH_TO_CSV: './test.csv'

